SET client_min_messages TO WARNING;

DROP FUNCTION IF EXISTS appreciationRecette(id INTEGER) CASCADE;

DROP FUNCTION IF EXISTS nbInvit(id INTEGER) CASCADE;

DROP FUNCTION IF EXISTS derniereInvit(id INTEGER) CASCADE;

DROP FUNCTION IF EXISTS aInviter(id INTEGER) CASCADE;

DROP FUNCTION IF EXISTS evenementImportant() CASCADE;

DROP TRIGGER IF EXISTS triggerDateEvenement ON REALISER_POUR;

DROP FUNCTION IF EXISTS verifierPersonne() CASCADE;

DROP TRIGGER IF EXISTS triggerPersonne ON PERSONNE;

DROP FUNCTION IF EXISTS verifierRangement() CASCADE;

DROP TRIGGER IF EXISTS triggerRangement ON RANGEMENT;

DROP INDEX IF EXISTS typeLien_index;

DROP INDEX IF EXISTS titre_index;

DROP TABLE IF EXISTS PERSONNE CASCADE; 

DROP TABLE IF EXISTS RANGEMENT CASCADE;

DROP TABLE IF EXISTS RECETTE CASCADE;

DROP TABLE IF EXISTS INGREDIENT CASCADE;

DROP TABLE IF EXISTS REALISER_POUR CASCADE;

DROP TABLE IF EXISTS CONTENIR CASCADE;

DROP TABLE IF EXISTS RANGER CASCADE;

DROP VIEW IF EXISTS LISTE_INVITATION_RECETTE CASCADE;

DROP VIEW IF EXISTS LISTE_A_INVITER CASCADE;